In [57]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb
from sklearn.ensemble import RandomForestRegressor

import warnings
warnings.filterwarnings('ignore')

In [2]:
data = pd.read_csv("database.csv")
data.columns

Index(['Date', 'Time', 'Latitude', 'Longitude', 'Type', 'Depth', 'Depth Error',
       'Depth Seismic Stations', 'Magnitude', 'Magnitude Type',
       'Magnitude Error', 'Magnitude Seismic Stations', 'Azimuthal Gap',
       'Horizontal Distance', 'Horizontal Error', 'Root Mean Square', 'ID',
       'Source', 'Location Source', 'Magnitude Source', 'Status'],
      dtype='object')

In [3]:
data.shape

(23412, 21)

In [4]:
data = data[['Date', 'Time', 'Latitude', 'Longitude', 'Depth', 'Magnitude']]  
data.head()  

Date      Time  Latitude  Longitude  Depth  Magnitude
0  01/02/1965  13:44:18    19.246    145.616  131.6        6.0
1  01/04/1965  11:29:49     1.863    127.352   80.0        5.8
2  01/05/1965  18:05:58   -20.579   -173.972   20.0        6.2
3  01/08/1965  18:49:43   -59.076    -23.557   15.0        5.8
4  01/09/1965  13:32:50    11.938    126.427   15.0        5.8

In [5]:
data.describe()

Latitude     Longitude         Depth     Magnitude
count  23412.000000  23412.000000  23412.000000  23412.000000
mean       1.679033     39.639961     70.767911      5.882531
std       30.113183    125.511959    122.651898      0.423066
min      -77.080000   -179.997000     -1.100000      5.500000
25%      -18.653000    -76.349750     14.522500      5.600000
50%       -3.568500    103.982000     33.000000      5.700000
75%       26.190750    145.026250     54.000000      6.000000
max       86.005000    179.998000    700.000000      9.100000

In [95]:
import datetime
import time

timestamp = []
for d, t in zip(data['Date'], data['Time']):
    try:
        ts = datetime.datetime.strptime(d+t+'', '%m/%d/%Y %H:%M:%S')
        timestamp.append(time.mktime(ts.timetuple()))
    except ValueError:
        # print('ValueError')
         timestamp.append('ValueError')
timeStamp = pd.Series(timestamp)
data['Timestamp'] = timeStamp.values
final_data = data.drop(['Date', 'Time'], axis=1)
final_data = final_data[final_data.Timestamp != 'ValueError']
final_data.head()


Empty DataFrame
Columns: [Latitude, Longitude, Depth, Magnitude, Timestamp]
Index: []

In [7]:
X = final_data[['Timestamp', 'Latitude', 'Longitude']]  
y = final_data[['Magnitude', 'Depth']]  

In [29]:
from sklearn import datasets

X, y = datasets.load_iris(return_X_y=True)

In [30]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import KFold, cross_val_score

In [31]:
clf = DecisionTreeClassifier(random_state=42)

In [32]:
k_folds = KFold(n_splits = 5)

scores = cross_val_score(clf, X, y, cv = k_folds)

In [105]:
#testing 
from sklearn import datasets
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import KFold, cross_val_score

X, y = datasets.load_iris(return_X_y=True)

clf = DecisionTreeClassifier(random_state=42)

k_folds = KFold(n_splits = 5)

scores = cross_val_score(clf, X, y, cv = k_folds)

print("Cross Validation Scores: ", scores)
print("Average CV Score: ", scores.mean())
print("Number of CV Scores used in Average: ", len(scores))


Cross Validation Scores:  [1.         1.         0.83333333 0.93333333 0.8       ]
Average CV Score:  0.9133333333333333
Number of CV Scores used in Average:  5


In [98]:
X_train, X_test, y_train, y_test = train_test_split(X_train, y_train, test_size=0.2, random_state=42)  
print(X_train.shape, X_test.shape, y_train.shape, X_test.shape)  

(89, 4) (23, 4) (89,) (23, 4)


In [86]:
reg = RandomForestRegressor(random_state=42)  
reg.fit(X_train, y_train)  
reg.predict(X_test)  

array([0.  , 1.  , 1.  , 0.  , 2.  , 1.11, 1.99, 0.  , 0.  , 2.  , 1.  ,
       0.  , 2.  , 1.  , 1.  , 0.  , 1.  , 1.  , 0.  , 0.  , 1.  , 1.  ,
       1.99, 0.  , 2.  , 1.  , 0.  , 0.  , 1.  , 1.96, 1.  , 2.  , 1.  ,
       2.  , 1.99, 0.  , 1.  , 0.  ])

In [ ]:
py -m pip install RandomForestRegressor

In [ ]:
pip install sklearn

In [36]:
reg = RandomForestRegressor(random_state=42)  
reg.fit(X_train, y_train)  
reg.predict(X_test)  

array([1.  , 0.  , 2.  , 1.  , 1.16, 0.  , 1.  , 1.98, 1.09, 1.  , 1.98,
       0.  , 0.  , 0.  , 0.  , 1.02, 2.  , 1.  , 1.  , 2.  , 0.  , 1.92,
       0.  , 2.  , 2.  , 1.99, 1.99, 2.  , 0.  , 0.  ])

In [ ]:
pip install  RandomForestRegressor

In [ ]:
pip install yfinance

In [47]:
reg = RandomForestRegressor(random_state=42)  
reg.fit(X_train, y_train)  
reg.predict(X_test)  

array([1.  , 0.  , 2.  , 1.  , 1.16, 0.  , 1.  , 1.98, 1.09, 1.  , 1.98,
       0.  , 0.  , 0.  , 0.  , 1.02, 2.  , 1.  , 1.  , 2.  , 0.  , 1.92,
       0.  , 2.  , 2.  , 1.99, 1.99, 2.  , 0.  , 0.  ])

In [102]:
#testing the model
reg.score(X_test, y_test)  


0.9999625

In [37]:
from sklearn.model_selection import GridSearchCV  
  
parameters = {'n_estimators':[10, 20, 50, 100, 200, 500]}  
  
grid_obj = GridSearchCV(reg, parameters)  
grid_fit = grid_obj.fit(X_train, y_train)  
best_fit = grid_fit.best_estimator_  
best_fit.predict(X_test)  

array([1. , 0. , 2. , 1. , 1.1, 0. , 1. , 2. , 1. , 1. , 2. , 0. , 0. ,
       0. , 0. , 1. , 2. , 1. , 1. , 2. , 0. , 1.9, 0. , 2. , 2. , 2. ,
       2. , 2. , 0. , 0. ])

In [106]:
#accuracy
best_fit.score(X_test, y_test)  

0.995

In [103]:
#neural model
from keras.models import Sequential  
from keras.layers import Dense  
  
def create_model(neurons, activation, optimizer, loss):  
    model = Sequential()  
    model.add(Dense(neurons, activation=activation, input_shape=(3,)))  
    model.add(Dense(neurons, activation=activation))  
    model.add(Dense(2, activation='softmax'))  
      
    model.compile(optimizer=optimizer, loss=loss, metrics=['accuracy'])  
      
    return model  

In [104]:
from keras.wrappers.scikit_learn import KerasClassifier  
  
model = KerasClassifier(build_fn=create_model, verbose=0)  
  
# neurons = [16, 64, 128, 256]  
neurons = [16]  
# batch_size = [10, 20, 50, 100]  
batch_size = [10]  
epochs = [10]  
# activation = ['relu', 'tanh', 'sigmoid', 'hard_sigmoid', 'linear', 'exponential']  
activation = ['sigmoid', 'relu']  
# optimizer = ['SGD', 'RMSprop', 'Adagrad', 'Adadelta', 'Adam', 'Adamax', 'Nadam']  
optimizer = ['SGD', 'Adadelta']  
loss = ['squared_hinge']  
  
param_grid = dict(neurons=neurons, batch_size=batch_size, epochs=epochs, activation=activation, optimizer=optimizer, loss=loss)  

In [ ]:
pip install keras

In [ ]:
pip install keras==2.12.0

In [ ]:
pip uninstall tensorflow
pip install tensorflow==2.12.0


In [ ]:
pip install tensorflow==2.12.0

In [ ]:
grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=-1)  
grid_result = grid.fit(X_train, y_train)  
  
print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))  
means = grid_result.CV_results_['mean_test_score']  
stds = grid_result.CV_results_['std_test_score']  
params = grid_result.CV_results_['params']  
for mean, stdev, param in zip(means, stds, params):  
    print("%f (%f) with: %r" % (mean, stdev, param))  

In [58]:
from sklearn.model_selection import GridSearchCV

In [60]:
model = Sequential()  
model.add(Dense(16, activation='relu', input_shape=(3,)))  
model.add(Dense(16, activation='relu'))  
model.add(Dense(2, activation='softmax'))  
  
model.compile(optimizer='SGD', loss='squared_hinge', metrics=['accuracy'])  

In [72]:
from sklearn.model_selection import GridSearchCV  
  
parameters = {'n_estimators':[10, 20, 50, 100, 200, 500]}  
  
grid_obj = GridSearchCV(reg, parameters)  
grid_fit = grid_obj.fit(X_train, y_train)  
best_fit = grid_fit.best_estimator_  
best_fit.predict(X_test)  

array([1. , 0. , 2. , 1. , 1.1, 0. , 1. , 2. , 1. , 1. , 2. , 0. , 0. ,
       0. , 0. , 1. , 2. , 1. , 1. , 2. , 0. , 1.9, 0. , 2. , 2. , 2. ,
       2. , 2. , 0. , 0. ])

In [71]:
#model testing
best_fit.score(X_test, y_test)  

0.9990461049284579